/**
 * Catalog domain types — generated by scripts/generate-catalog.ts from the
 * PDFs under quality/. This module defines the SHAPE of the catalog only;
 * it never computes a price (that stays exclusively in src/pricing/, per
 * tech.md's pricing invariant). Every CatalogItem maps onto one of the
 * existing pricing ProductIds so the pricing engine needs zero changes.
 *
 * The manifest is versioned (schemaVersion + catalogVersion) so a
 * historic order can always be traced back to the exact catalog item
 * it was built from, even after the catalog is regenerated.
 */

import type { ProductId, Silhouette, Tier } from "../pricing/priceBook.js";

/** Catalog tiers mirror the pricing Tier exactly — no separate vocabulary. */
export type CatalogTier = Tier;

/** How reliably this source PDF's page text/structure could be parsed. */
export type ExtractionQuality = "text" | "image-only" | "partial";

export interface CatalogSourceInfo {
  /** Stable slug id, e.g. "basic-cotton-polo". Referenced by items/variants. */
  id: string;
  /** Path relative to the quality/ folder, e.g. "Basic/cotton polo.pdf". */
  relativePath: string;
  /** SHA-256 of the PDF file contents at ingestion time — detects drift. */
  sha256: string;
  pageCount: number;
  extractionQuality: ExtractionQuality;
}

export type CatalogGroupKind = "category" | "brand";

/** Step 2 of the flow: brands (Premium) or garment categories (Basic/Standard). */
export interface CatalogGroup {
  id: string;
  tier: CatalogTier;
  kind: CatalogGroupKind;
  label: string;
  /** Ordered ids of CatalogItem belonging to this group. */
  itemIds: string[];
}

export type CatalogImageKind = "rendered-page" | "external-link" | "placeholder";

export interface CatalogImageRef {
  kind: CatalogImageKind;
  /** Path relative to assets/catalog/, e.g. "basic-cotton-polo/page-001.jpg". Present for rendered-page and downloaded external-link images. */
  localPath?: string;
  /** Original external URL the image was sourced from (Stellars swatch links), kept for traceability even after download. */
  sourceUrl?: string;
  width?: number;
  height?: number;
}

/** A colour option for a CatalogItem. */
export interface CatalogVariant {
  id: string;
  colorName: string;
  colorCode?: string;
  /** 1-indexed source PDF page this variant's own photo (if any) came from. */
  sourcePage?: number;
  image: CatalogImageRef;
}

/** Step 3 of the flow: one purchasable style/design within a group. */
export interface CatalogItem {
  id: string;
  groupId: string;
  tier: CatalogTier;
  /** Display label, e.g. "Quality No. 380T — Mercerised Cotton". */
  label: string;
  /** Maps this catalog item onto the pricing engine's product SKU. Pricing is computed from (tier, productId, qty) exactly as before — unaffected by brand/style. */
  productId: ProductId;
  garmentType: Silhouette;
  styleCode?: string;
  fabric?: string;
  gsm?: number;
  sourceId: string;
  /** 1-indexed primary source page this item's data/photo was extracted from. */
  sourcePage: number;
  previewImage: CatalogImageRef;
  /** Colour options. Empty when no colour data could be extracted. */
  variants: CatalogVariant[];
  /**
   * True when this item was produced by the generic image-only fallback
   * parser (no reliable text — e.g. Reebok, Van Heusen) or otherwise
   * needs a human to verify label/productId/variants before trusting it
   * for a real order.
   */
  needsReview: boolean;
}

export interface CatalogManifest {
  /** Bump when the shape of this file changes in a breaking way. */
  schemaVersion: number;
  /** Bump when the catalog CONTENT changes meaningfully (new PDFs, re-ingested pages). Stored on every order for traceability. */
  catalogVersion: string;
  generatedAt: string;
  sources: CatalogSourceInfo[];
  groups: CatalogGroup[];
  items: CatalogItem[];
}

/** Manual, hand-maintained patches applied on top of auto-extracted data — see scripts/generate-catalog.ts. Lets the shop owner fix a mis-parsed label/colour without hand-editing the generated JSON (which gets overwritten on every re-run). */
export interface CatalogOverridesFile {
  /** Keyed by CatalogItem.id. Partial fields here are shallow-merged over the auto-extracted item. */
  items?: Record<string, Partial<Pick<CatalogItem, "label" | "productId" | "garmentType" | "styleCode" | "fabric" | "gsm" | "needsReview">>>;
  /** Keyed by CatalogVariant.id. */
  variants?: Record<string, Partial<Pick<CatalogVariant, "colorName" | "colorCode">>>;
}
